server:
  port: 8083
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: dev
  resources:
    static-locations: classpath:/META-INF/resources, classpath:/resources, classpath:/static, classpath:/public, file:morty/frontend/dist
server:
  tomcat:
    max-threads: 20