package be.ordina.spring.demo;

public enum RickAndMortyQuote {

	I_WANT_MY_SZECHUAN_SAUCE,
	WUBBA_LUBBA_DUB_DUB,

	MR_MEESEEKS_SPAWN,

	IM_MR_MEESEEKS_LOOK_AT_ME,
	HEY_THERE_IM_MR_MEESEEKS,
	LOOK_AT_ME_IM_MR_MEESEEKS,

	EXISTENCE_IS_PAIN,
	NOW_I_LL_NEVER_DIE,

	YES_SIRREEE,
	OOOH_OKAY,
	OOOH_YEAH_CAN_DO,

	PLEASE_GIVE_ME_SOME_SZECHUAN_SAUCE,

	ALL_DONE,

	CAN_I_TAKE_YOUR_ORDER_PLEASE,
	SORRY_NO_LUCK,
	YOU_ARE_A_WINNER

}
